# Generated by Django 5.1.4 on 2025-01-01 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="task_priority",
            field=models.CharField(
                choices=[("L", "LOW"), ("H", "HIGH"), ("M", "MED")],
                max_length=1,
                null=True,
            ),
        ),
    ]
