# Generated by Django 5.1.4 on 2025-01-01 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0002_task_task_priority"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="task_priority",
        ),
        migrations.AddField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[("L", "LOW"), ("M", "MED"), ("H", "HIGH")],
                default="M",
                max_length=1,
            ),
        ),
    ]
