# Generated by Django 5.1.4 on 2025-01-01 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0003_remove_task_task_priority_task_priority"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[("H", "HIGH"), ("M", "MED"), ("L", "LOW")],
                default="M",
                max_length=1,
            ),
        ),
    ]
